BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[News] (
    [id] NVARCHAR(1000) NOT NULL CONSTRAINT [News_id_df] DEFAULT NEWID(),
    [slug] NVARCHAR(1000) NOT NULL,
    [title] NVARCHAR(1000) NOT NULL,
    [image] NVARCHAR(1000) NOT NULL,
    [date] DATETIME2 NOT NULL,
    [content] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [News_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
