BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[News] DROP CONSTRAINT [News_id_df];
ALTER TABLE [dbo].[News] ALTER COLUMN [date] NVARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[News] ADD CONSTRAINT [News_id_df] DEFAULT NEWID() FOR [id];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
